#!/usr/bin/env python3
"""Convert generated WAV files into C arrays for the ESP32 sketch.

Reads sounds/rocket_thrust.wav, sounds/explosion.wav, sounds/wind.wav and
sounds/lightning.wav (8-bit mono 16 kHz) and writes
esp32LanderComposite/src/audio_data.h with PROGMEM byte arrays.
"""
import os
import struct
import wave

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "esp32LanderComposite", "src", "audio_data.h")

def read_wav(path):
    with wave.open(path, "rb") as w:
        assert w.getnchannels() == 1
        assert w.getsampwidth() == 1
        assert w.getframerate() == 16000
        data = w.readframes(w.getnframes())
    return data

def emit(path, name, fh):
    data = read_wav(path)
    fh.write(f"static const uint8_t PROGMEM {name}[{len(data)}] = {{\n")
    for i in range(0, len(data), 20):
        row = ", ".join(f"{b}" for b in data[i:i+20])
        fh.write(f"    {row},\n")
    fh.write(f"}};\n\n")
    return len(data)

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    thrust = os.path.join(here, "rocket_thrust.wav")
    expl = os.path.join(here, "explosion.wav")
    wind = os.path.join(here, "wind.wav")
    lightning = os.path.join(here, "lightning.wav")
    with open(OUT, "w") as fh:
        fh.write("/* Generated by sounds/convert_wav.py — do not edit. */\n")
        fh.write("#ifndef AUDIO_DATA_H\n#define AUDIO_DATA_H\n\n")
        fh.write('#include <Arduino.h>\n#include <pgmspace.h>\n\n')
        n_t = emit(thrust, "THRUST_SOUND", fh)
        n_e = emit(expl, "EXPLOSION_SOUND", fh)
        n_w = emit(wind, "WIND_SOUND", fh)
        n_l = emit(lightning, "LIGHTNING_SOUND", fh)
        fh.write(f"const int THRUST_SOUND_LEN = {n_t};\n")
        fh.write(f"const int EXPLOSION_SOUND_LEN = {n_e};\n")
        fh.write(f"const int WIND_SOUND_LEN = {n_w};\n")
        fh.write(f"const int LIGHTNING_SOUND_LEN = {n_l};\n\n")
        fh.write("#endif\n")
    print(f"wrote {OUT}: thrust={n_t}, explosion={n_e}, wind={n_w}, lightning={n_l}")

if __name__ == "__main__":
    main()
